---
name: "Master"

on:
  push:

jobs:
  terraform:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@6cd4c5330814aeabc8f1216cbfc3f48842d2ed2d
        with:
          php-version: '7.0'
          tools: 'composer:v1, prestissimo'
          coverage: 'none'