name: "test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print something
        run: |
          echo "Hello World"
          git log
          sleep 120
          ls -la

